embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

semantic_search:
  search_type: "similarity_score_threshold"
  top_k: 2
  similarity_score_limit: 0.25

chroma_db:
  collection_name: "faq"