# chunking:
#   separators:
#     - "\n\n"
#     - "\n"
#     - "."
#     - " "
#   chunk_size: 500
#   chunk_overlap: 20

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

semantic_search:
  top_k: 2
  similarity_score_limit: 0.25

chroma_db:
  collection_name: "faq"